#!/bin/sh
output="$1"
cfgid="xmonad-test"
cache=$( dirname "$1" )

mkfifo cabalout

echo "[XMonad-Test Build] Begin"
cabal build "exe:$cfgid" | tee cabalout &
if ! grep -q "Up to date" <cabalout ; then
  cabal install "exe:$cfgid" \
    --installdir="$cache" --install-method=copy \
    --overwrite-policy=always
  ln -sf "$cache/$cfgid" "$output"
  # To make next Up-To-Date build faster
  cabal build "exe:$cfgid"
fi
echo "[XMonad-Test Build] End"
